### ISSUE TITLE
icebergs cannot restart from distributed restart files

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/icebergs#52]
After commit 0348755 to fix the issue with large number of bergs (PR #51 ) the icebergs cannot restart from distributed files and such attempt causes the following crash:

```
Rank 64 [Mon Jun 19 11:01:23 2017] [c0-0c2s14n1] Fatal error in MPI_Allreduce: Message truncated, error stack:
MPI_Allreduce(1007).................: MPI_Allreduce(sbuf=0x7ffffffe70f0, rbuf=0x7ffffffe7070, count=1, dtype=0x4c000430, MPI_SUM, comm=0x84000004) failed
MPIR_Allreduce_impl(850)............:
MPIR_CRAY_Allreduce(346)............:
MPIR_Allreduce_intra(485)...........:
MPIC_Sendrecv(533)..................:
MPIDI_CH3U_Request_unpack_uebuf(618): Message truncated; 8 bytes received but buffer size is 4
MPIR_Allreduce_intra(485)...........:
MPIDI_CH3U_Receive_data_found(144)..: Message from rank 0 and tag 14 truncated; 8 bytes received but buffer size is 4

forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
fms_MOM6_SIS2_com  000000000180C124  mpp_mod_mp_mpp_su          21  mpp_sum_mpi.h
fms_MOM6_SIS2_com  000000000069F429  ice_bergs_framewo        4678  icebergs_framework.F90
fms_MOM6_SIS2_com  00000000006BE71C  ice_bergs_io_mp_r         715  icebergs_io.F90
fms_MOM6_SIS2_com  000000000067B58F  ice_bergs_mp_iceb         132  icebergs.F90
fms_MOM6_SIS2_com  000000000049B534  ice_model_mod_mp_        2462  ice_model.F90
fms_MOM6_SIS2_com  000000000040BA51  coupler_main_IP_c        1668  coupler_main.F90
```

This can be reproduce by trying to restart the experiment  ice_ocean_SIS2/SIS2_icebergs with a SIS_layout other than the default 1,1.

**Comment by adcroft** [comment]
Using IO_LAYOUT=2,1 in SIS2_bergs_cgrid (which is actively tested) and IO_LAYOUT=4,1 in SIS2_icebergs (is semi-retired as a test), I was not able to reproduce this problem.

The error is coming from below an mpp_sum() and I don't know how the recent changes could have affected the communications - there are now new barriers or halo-updates. Since I can't make this fail we need to compare the setup in the XML with what is in the repo.

**Comment by adcroft** [comment]
I just checked this wasn't compiler specific: I was using gnu but I can't reproduce the problem with intel either.

**Comment by nikizadehgfdl** [comment]
I used layout = "16,8"   io_layout = "1,4", with intel16. Let me try SIS2_bergs_cgrid.

**Comment by adcroft** [comment]
OK - that breaks it. There is a mpp_sync_self deep down that not all PEs are calling because some files are blank. This is happening because of that work around to avoid zero-length arrays.

**Comment by adcroft** [comment]
As far as I can see, we have a choice of a SEGV because the arrays have zero length (for which we already wrote a work around) or a hang in MPP because of the sync within i/o.

**Comment by adcroft** [comment]
This is in mpp_io (read_compressed.h):
![image](https://user-images.githubusercontent.com/5859571/27353380-c9875b70-55d1-11e7-9ee9-b5d6e3d5deaf.png)
The array is unallocated because there are zero bergs in the file but the size(data) is showing a random large value. I believe size requires the argument to be allocated.
